name: Receive repository dispatch event

on:
  repository_dispatch:
    types: [dispatch-event]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Event info
        run: |
          echo PROOF-API SHA: ${{ github.event.client_payload.sha }}
          echo PROOF-API REF: ${{ github.event.client_payload.ref }}
          echo PROOF-API PR No.: ${{ github.event.client_payload.pr }}
      - name: Do something
        run: echo "I'm doing something!!!"
